Metrics/LineLength:
  Max: 160

Metrics/BlockLength:
  Enabled: False

Layout/IndentationWidth:
  Description: 'Use 2 spaces for indentation.'
  StyleGuide: '#spaces-indentation'
  Enabled: true
  Width: 2
  IgnoredPatterns: []

Layout/MultilineHashBraceLayout:
  Enabled: true

Documentation:
  Enabled: false

Layout/EndOfLine:
  Enabled: False

Style/MixinUsage:
  Enabled: False

Naming/AccessorMethodName:
  Enabled: False

Metrics/BlockLength:
  Max: 50